// <auto-generated />
using System;
using Demo.Core.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo.Core.Migrations
{
    [DbContext(typeof(FMTContext))]
    partial class FMTContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Demo.Core.Entity.BagCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescription");

                    b.Property<int?>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedOn");

                    b.HasKey("Id");

                    b.ToTable("BagCategory");
                });

            modelBuilder.Entity("Demo.Core.Entity.BagType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("BagCategoryNo");

                    b.Property<string>("BagDesc");

                    b.Property<string>("BagName")
                        .HasMaxLength(50);

                    b.Property<int?>("CreatedBy")
                        .IsRequired();

                    b.Property<DateTime?>("CreatedOn")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<int?>("LastModifiedBy");

                    b.Property<DateTime?>("LastModifiedOn");

                    b.Property<decimal>("TareWeight");

                    b.HasKey("Id");

                    b.ToTable("BagType");
                });
#pragma warning restore 612, 618
        }
    }
}
